#!/bin/bash

oldpythonpath="$PYTHONPATH"
oldpythonhome="$PYTHONHOME"
unset PYTHONPATH
unset PYTHONHOME
source /n/sw/envs/squeue/bin/activate
#(/usr/local/bin/rc-squeue "$@")
(./rc-squeue "$@")
exitcode=$?
deactivate
export PYTHONPATH=$oldpythonpath
export PYTHONHOME=$oldpythonhome
exit $exitcode

